apiVersion: apps/v1
kind: Deployment
metadata:
  name: bob-deployment-mte
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bob
  template:
    metadata:
      labels:
        app: bob
    spec:
      containers:
      - name: bob
        image: acrbob.azurecr.io/bob/bob:latest
        env:
        - name: IP
          value: "mte-relay-service-bob"  # Use the service name
        - name: PORT
          value: "8080"
        - name: UPSTREAM
          value: "http://131.145.2.139" # Set this to the output of the alice deployment
        ports:
        - containerPort: 80
      - name: azure-mte-api-relay
        image: arcmktplaceprod.azurecr.io/eclypses1708534446098/mte-api-relay/images/azure-marketplace/mte-api-relay:4.3.2-latest
        ports:
        - containerPort: 8080
        env:
          - name: CLIENT_ID_SECRET
            value: "SecretSecretSecretSecret"
          - name: UPSTREAM
            value: "http://bob-service-internal:80"  # Use the internal service name and port
          - name: OUTBOUND_TOKEN
            value: "TokenTokenTokenToken"
          - name: SECRET
            value: "SecretSecretSecretSecret"
          - name: DEBUG
            value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: bob-service-external
spec:
  type: LoadBalancer
  selector:
    app: bob
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mte-relay-service-bob
spec:
  type: LoadBalancer
  selector:
    app: bob
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
